---
- hosts: esi_ha_cluster
  gather_facts: false
  tasks:
    - block:
        - name: authenticate to ovirt
          delegate_to: localhost
          run_once: true
          ovirt_auth:
            state: present

        - name: delete virtual machines
          delegate_to: localhost
          ovirt_vm:
            state: absent
            name: "{{ inventory_hostname }}"

      always:
        - name: revoke sso token
          when: ovirt_auth is defined
          delegate_to: localhost
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
