all:
  hosts:
    esi-undercloud.massopen.cloud:
      ctlplane_ip: 192.168.24.1/24
      public_ip: 129.10.5.140
    esi-controller-0.massopen.cloud:
      ctlplane_ip: 192.168.24.10/24
      public_ip: 129.10.5.141
    esi-controller-1.massopen.cloud:
      ctlplane_ip: 192.168.24.11/24
      public_ip: 129.10.5.142
    esi-controller-2.massopen.cloud:
      ctlplane_ip: 192.168.24.12/24
      public_ip: 129.10.5.143
