---
- hosts: esi_ha_cluster
  gather_facts: false
  tasks:
    - block:
        - name: authenticate to ovirt
          delegate_to: localhost
          run_once: true
          ovirt_auth:

        - name: create {{ inventory_hostname }}
          delegate_to: localhost
          ovirt_vm:
            auth: "{{ ovirt_auth }}"
            cluster: KZN2
            name: "{{ inventory_hostname }}"
            state: present
            template: esi-base-template
            clone: true
            serial_console: true
            cloud_init_persist: true
            cloud_init:
              host_name: "{{ inventory_hostname }}"
              dns_servers: "8.8.8.8 8.8.4.4"
              dns_search: massopen.cloud
              authorized_ssh_keys: |-
                ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHU+dRblINH9VOKWKluyyE1xz0GG6YMIiTCgUlDrEzvybC0Y0luIj87rQFHmihYFrmYdrCe2v2dFo1LggJEMPh3jfrXzJVl7KjbTOdsUSVwWCHD07uAiyNmH7aNGFuS4B6oiQj5NSTzl5C0Mvt/JIZmkky2305tZoF40bGlHP/U3tXoU+QPRqV44HR0AdkMArHADQoR/cpEQJantNuQsV2BouzfOJ8GcFLDU2ZPESgubrd4CxQ7p2+uujl0WsTsz0Ip3FkJINBHBnOGM9NteHVsiGJgmg3oeOhcH31bjYOToRNKvjAiepAsQMjhfm3GE850DcFJO6kEGD8umbhRiXZIfGJkqw1HWzcaN09q9cOWczMUytGBy6BGc7eNdf03F9FHLOO8c5gcA6Sd7rJFZD6LbRv+O8mtbLpL9Bi41I/5vNgNo0HI0Z2w56r9F8rRQ+jy4HR29hvV5yR7LZHC2kJ3TZiZBeqy5UG6SlQI4fOq1JHQ9/IzT4wV+sxQz38k3Yir6RE/Yg9N8wTMxpYG5/LsXa/eGRThCRbbaY5IgSK4NAWDDhMEt9TqTwrNSzEMi6Xv5DLROtyctUNN5fcN2M+evcJ4GqUgaw87e6Jk89cyQj/f3XLRjO2Yxudl5uLDd4f5aOnMJxsr8+3j5xMe8BNM9VkZqhPM/FEhi40xAl9lQ==
              timezone: "US/Eastern"
            cloud_init_nics:
              - nic_name: eth0
                nic_on_boot: true
                nic_boot_protocol: static
                nic_ip_address: "{{ public_ip|ipv4('address') }}"
                nic_gateway: 129.10.5.1
                nic_netmask: 255.255.255.0
              - nic_name: eth1
                nic_on_boot: true
                nic_boot_protocol: static
                nic_ip_address: "{{ ctlplane_ip|ipv4('address') }}"
                nic_gateway: ""
                nic_netmask: "{{ ctlplane_ip|ipv4('netmask') }}"

      always:
        - name: revoke sso token
          delegate_to: localhost
          when: ovirt_auth is defined
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
