---
- hosts: esi-undercloud.massopen.cloud
  tags: [prep.host]
  tasks:
    - name: get current hostname
      command: hostname -f
      register: hostname
      changed_when: false

    - name: set hostname to inventory hostname
      command: hostnamectl set-hostname {{ inventory_hostname }}
      when: hostname.stdout != inventory_hostname

    - name: ensure entry in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: |-
          {{ ansible_default_ipv4.address }}  {{ inventory_hostname }}

- hosts: esi-undercloud.massopen.cloud
  tags: [prep.user]
  tasks:
    - name: create stack user
      user:
        name: stack
        generate_ssh_key: true
        ssh_key_bits: 4096

    - name: configure stack user authorized_keys
      authorized_key:
        user: stack
        key: "{{ item }}"
      loop: "{{ stack_authorized_keys }}"

    - name: enable sudo access for stack user
      copy:
        dest: /etc/sudoers.d/stack
        content: |-
          stack ALL=(root) NOPASSWD:ALL
        mode: 0440
        owner: root
        group: root

- hosts: esi-undercloud.massopen.cloud
  tags: [prep.packages]
  tasks:

    ## LKS: we're using 'dnf' instead of 'package' because we need
    ## disable_gpg_check. Consider pre-fetching the keys instead.
    - name: install tripleo-repos
      dnf:
        name: https://trunk.rdoproject.org/centos8/component/tripleo/current/python3-tripleo-repos-{{ tripleo_repos_version }}.el8.noarch.rpm
        state: installed
        disable_gpg_check: true

    - name: activate openstack repostories
      command: >-
        tripleo-repos -b {{ openstack_release }} current ceph

    - name: upgrade packages
      package:
        name: '*'
        state: latest

    - name: install tripleo
      dnf:
        name: "{{ packages }}"
      vars:
        packages:
          - python3-tripleoclient
          - ceph-ansible

- hosts: esi-undercloud.massopen.cloud
  tags: [prep.undercloud]
  vars:
    ansible_user: stack

  tasks:
    - name: fetch undercloud.conf.sample
      fetch:
        src: /usr/share/python-tripleoclient/undercloud.conf.sample
        dest: ./undercloud.conf.sample
        flat: true

    - name: install undercloud.conf
      copy:
        src: undercloud.conf
        dest: undercloud.conf

    - name: install hiera overrides
      copy:
        src: hiera-overrides.yml
        dest: ./hiera-overrides.yml
